import {
  createSystem,
  defaultConfig,
  defineConfig,
  defineSlotRecipe,
} from '@chakra-ui/react';
import type { SystemConfig } from '@chakra-ui/react';

export const previewSlotRecipeKeys = {
  feedback: 'chakraEmailPreviewFeedback',
  inspector: 'chakraEmailPreviewInspector',
  templates: 'chakraEmailPreviewTemplates',
  viewer: 'chakraEmailPreviewViewer',
  workspace: 'chakraEmailPreviewWorkspace',
} as const;

export const previewWorkspaceSlotRecipe = defineSlotRecipe({
  className: 'chakra-email-preview-workspace',
  slots: [
    'root',
    'header',
    'brand',
    'brandMark',
    'brandCopy',
    'headerActions',
    'modeToggle',
    'connection',
    'connectionDot',
    'body',
    'sidebar',
    'sidebarHeader',
    'templateNav',
    'sidebarFooter',
    'main',
    'heading',
    'eyebrow',
    'title',
    'subject',
    'path',
    'actions',
    'viewportControl',
    'remoteControl',
    'lintSummary',
    'secondaryAction',
    'primaryAction',
    'content',
    'inspectorPanel',
  ],
  base: {
    root: {
      h: '100dvh',
      gridTemplateRows: '48px minmax(0, 1fr)',
      color: 'preview.text',
      bg: 'preview.canvas',
    },
    header: {
      zIndex: 'docked',
      alignItems: 'center',
      justifyContent: 'space-between',
      px: '3',
      gap: '3',
      borderBottomWidth: '1px',
      borderColor: 'preview.border',
      bg: 'preview.chrome',
    },
    brand: { gap: '2', alignItems: 'center', flexShrink: 0 },
    brandMark: {
      boxSize: '7',
      placeItems: 'center',
      borderWidth: '1px',
      borderColor: 'preview.borderStrong',
      borderRadius: 'sm',
      color: 'preview.accentInk',
      bg: 'preview.accent',
      boxShadow: 'previewAccent',
      fontSize: 'sm',
      fontWeight: 'extrabold',
      letterSpacing: '-0.05em',
    },
    brandCopy: { gap: '0', display: { base: 'none', md: 'flex' } },
    headerActions: { alignItems: 'center', gap: '2' },
    modeToggle: {
      borderWidth: '1px',
      borderColor: 'preview.border',
      borderRadius: 'sm',
      color: 'preview.textSubtle',
      bg: 'preview.overlay',
    },
    connection: {
      display: { base: 'none', sm: 'flex' },
      alignItems: 'center',
      gap: '2',
      px: '2',
      color: 'preview.textMuted',
      fontSize: '2xs',
      bg: 'transparent',
    },
    connectionDot: { boxSize: '2', borderRadius: 'full' },
    body: { minH: '0', minW: '0', gridTemplateColumns: 'minmax(0, 1fr)' },
    sidebar: {
      minH: '0',
      gridTemplateRows: 'auto minmax(0, 1fr) auto',
      borderRightWidth: '1px',
      borderColor: 'preview.border',
      bg: 'preview.sidebar',
    },
    sidebarHeader: {
      alignItems: 'center',
      justifyContent: 'space-between',
      px: '4',
      pt: '4',
      pb: '3',
      color: 'preview.textSubtle',
      fontSize: '2xs',
      fontWeight: 'extrabold',
      letterSpacing: '0.09em',
      textTransform: 'uppercase',
    },
    templateNav: {
      minH: '0',
      px: '2.5',
      pb: '4',
      overflowY: 'auto',
      scrollbarColor: 'var(--chakra-colors-preview-border) transparent',
      scrollbarWidth: 'thin',
    },
    sidebarFooter: {
      gap: '2',
      alignItems: 'center',
      px: '4',
      py: '3',
      borderTopWidth: '1px',
      borderColor: 'preview.border',
      color: 'preview.textMuted',
      fontSize: '2xs',
    },
    main: {
      minW: '0',
      minH: '0',
      display: 'flex',
      flexDirection: 'column',
      overflow: 'hidden',
    },
    heading: {
      minW: '0',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '2',
      px: '3',
      py: '1.5',
      flexWrap: 'wrap',
      flexShrink: 0,
      borderBottomWidth: '1px',
      borderColor: 'preview.border',
      bg: 'preview.chrome',
    },
    eyebrow: {
      mb: '1',
      color: 'preview.textSubtle',
      fontSize: '2xs',
      fontWeight: 'extrabold',
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
    },
    title: {
      minW: '0',
      flex: '1',
      overflow: 'hidden',
      color: 'preview.text',
      fontSize: 'xs',
      fontWeight: 'semibold',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    subject: {
      display: 'block',
      maxW: '600px',
      mt: '1',
      overflow: 'hidden',
      color: 'preview.textSubtle',
      fontSize: 'xs',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    path: {
      display: 'block',
      maxW: '500px',
      mt: '1',
      overflow: 'hidden',
      color: 'preview.textMuted',
      bg: 'transparent',
      fontFamily: 'previewMono',
      fontSize: '2xs',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    actions: { alignItems: 'center', gap: '1.5', flexWrap: 'wrap' },
    viewportControl: {
      p: '1',
      borderWidth: '1px',
      borderColor: 'preview.border',
      borderRadius: 'sm',
      bg: 'preview.panel',
    },
    remoteControl: {
      display: 'flex',
      minH: '8',
      alignItems: 'center',
      gap: '2',
      px: '2.5',
      borderWidth: '1px',
      borderColor: 'preview.border',
      borderRadius: 'sm',
      color: 'preview.textSubtle',
      bg: 'preview.panel',
      fontSize: '2xs',
      fontWeight: 'bold',
    },
    lintSummary: {
      display: 'flex',
      minH: '8',
      alignItems: 'center',
      gap: '1.5',
      px: '3',
      borderWidth: '1px',
      borderRadius: 'sm',
      bg: 'preview.panel',
      fontSize: '2xs',
    },
    secondaryAction: {
      minH: '8',
      h: '8',
      px: '3',
      gap: '2',
      borderWidth: '1px',
      borderColor: 'preview.borderStrong',
      borderRadius: 'sm',
      color: 'preview.textSubtle',
      bg: 'preview.panel',
      fontSize: 'xs',
      fontWeight: 'bold',
      _hover: { color: 'preview.text', bg: 'preview.hover' },
    },
    primaryAction: {
      minH: '8',
      h: '8',
      px: '3',
      gap: '2',
      borderWidth: '1px',
      borderColor: 'preview.successBorder',
      borderRadius: 'sm',
      color: 'preview.accentInk',
      bg: 'preview.accent',
      boxShadow: 'previewAccent',
      fontSize: 'xs',
      fontWeight: 'extrabold',
      _hover: { bg: 'preview.accentHover' },
    },
    content: {
      minH: '0',
      minW: '0',
      flex: '1',
      gridTemplateColumns: 'minmax(0, 1fr)',
      overflow: 'hidden',
    },
    inspectorPanel: { minH: '0', minW: '0', overflow: 'auto' },
  },
  variants: {
    templatesOpen: {
      true: {
        body: {
          gridTemplateColumns: {
            base: 'minmax(0, 1fr)',
            md: '220px minmax(0, 1fr)',
          },
        },
        sidebar: { display: 'grid' },
        main: { display: { base: 'none', md: 'flex' } },
      },
      false: { sidebar: { display: 'none' } },
    },
    inspectorOpen: {
      true: {
        content: {
          gridTemplateColumns: {
            base: 'minmax(0, 1fr)',
            md: 'minmax(0, 1fr) 280px',
          },
        },
      },
      false: { inspectorPanel: { display: 'none' } },
    },
  },
});

export const previewTemplatesSlotRecipe = defineSlotRecipe({
  className: 'chakra-email-preview-templates',
  slots: [
    'loading',
    'empty',
    'list',
    'item',
    'avatar',
    'content',
    'name',
    'path',
    'chevron',
  ],
  base: {
    loading: { gap: '2', py: '2' },
    empty: {
      alignItems: 'center',
      gap: '2',
      py: '8',
      px: '3',
      color: 'preview.textMuted',
      textAlign: 'center',
    },
    list: { gap: '0.5' },
    item: {
      display: 'grid',
      gridTemplateColumns: '16px minmax(0, 1fr)',
      gap: '2',
      alignItems: 'center',
      w: 'full',
      minH: '8',
      h: '8',
      px: '2',
      py: '2',
      borderWidth: '1px',
      borderRadius: 'md',
      textAlign: 'start',
      _hover: { color: 'preview.text', bg: 'preview.hover' },
    },
    avatar: {
      boxSize: '4',
      placeItems: 'center',
      color: 'inherit',
      bg: 'transparent',
    },
    content: { minW: '0', gap: '0.5' },
    name: {
      overflow: 'hidden',
      color: 'inherit',
      fontSize: 'xs',
      fontWeight: 'medium',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    path: {
      display: 'none',
      overflow: 'hidden',
      color: 'preview.textMuted',
      fontFamily: 'previewMono',
      fontSize: '2xs',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    chevron: { fontSize: 'xl' },
  },
  variants: {
    selected: {
      true: {
        item: {
          borderColor: 'transparent',
          color: 'preview.text',
          bg: 'preview.accentSoft',
        },
        avatar: { color: 'preview.text', bg: 'transparent' },
        chevron: { color: 'preview.accent' },
      },
      false: {
        item: {
          borderColor: 'transparent',
          color: 'preview.textSubtle',
          bg: 'transparent',
        },
        avatar: { color: 'preview.textMuted', bg: 'transparent' },
        chevron: { color: 'preview.textMuted' },
      },
    },
  },
  defaultVariants: { selected: false },
});

export const previewViewerSlotRecipe = defineSlotRecipe({
  className: 'chakra-email-preview-viewer',
  slots: [
    'root',
    'tabs',
    'tab',
    'content',
    'empty',
    'emptyMark',
    'surface',
    'surfaceHeader',
    'stage',
    'modeGroup',
    'modeButton',
    'frame',
    'codeRoot',
    'codeHeader',
    'code',
    'overlay',
  ],
  base: {
    root: {
      minW: '0',
      minH: '0',
      display: 'grid',
      gridTemplateRows: 'minmax(0, 1fr)',
      overflow: 'hidden',
      borderRadius: '0',
      bg: 'preview.panel',
      boxShadow: 'none',
    },
    tabs: {
      alignItems: 'center',
      gap: '0.5',
      p: '0.5',
      borderWidth: '1px',
      borderColor: 'preview.border',
      borderRadius: 'md',
      bg: 'preview.panel',
      flexShrink: 0,
    },
    tab: {
      color: 'preview.textMuted',
      bg: 'transparent',
      fontSize: 'xs',
      fontWeight: 'medium',
      borderRadius: 'sm',
      _hover: { color: 'preview.text', bg: 'preview.hover' },
      _selected: { color: 'preview.text', bg: 'preview.soft' },
    },
    content: { minH: '0', h: 'full', p: '0' },
    empty: {
      h: 'full',
      minH: '0',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '3',
      color: 'preview.textMuted',
      textAlign: 'center',
    },
    emptyMark: {
      boxSize: '16',
      placeItems: 'center',
      borderRadius: 'md',
      color: 'preview.accentInk',
      bg: 'preview.accent',
      fontWeight: 'black',
    },
    surface: {
      bg: 'preview.soft',
      position: 'relative',
      h: 'full',
      minH: '0',
      display: 'grid',
      gridTemplateRows: 'minmax(0, 1fr) auto',
      overflow: 'hidden',
    },
    stage: {
      minH: '0',
      minW: '0',
      alignItems: 'center',
      justifyContent: 'center',
      p: { base: '3', md: '8' },
      overflow: 'hidden',
    },
    surfaceHeader: {
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '3',
      flexWrap: 'wrap',
      px: '3',
      py: '1',
      borderTopWidth: '1px',
      borderColor: 'preview.border',
      bg: 'preview.chrome',
      color: 'preview.textMuted',
      fontSize: '2xs',
      fontWeight: 'bold',
      textTransform: 'none',
    },
    modeGroup: {
      alignItems: 'center',
      gap: '1',
      borderRadius: 'sm',
      bg: 'preview.panel',
    },
    modeButton: {
      minH: '7',
      h: '7',
      px: '2',
      borderRadius: 'sm',
      fontSize: '2xs',
      fontWeight: 'extrabold',
      textTransform: 'none',
    },
    frame: {
      position: 'relative',
      flexShrink: 0,
      maxW: '100%',
      minW: 'min(280px, 100%)',
      h: '100%',
      minH: '120px',
      maxH: '100%',
      overflow: 'hidden',
      resize: 'both',
      borderWidth: '1px',
      borderColor: 'preview.border',
      borderRadius: 'sm',
      boxShadow: '0 2px 12px rgba(0, 0, 0, 0.06)',
    },
    codeRoot: {
      position: 'relative',
      h: 'full',
      minH: '0',
      gridTemplateRows: '42px minmax(0, 1fr)',
      bg: 'preview.codeCanvas',
    },
    codeHeader: {
      alignItems: 'center',
      justifyContent: 'space-between',
      px: '4',
      borderBottomWidth: '1px',
      borderColor: 'preview.border',
      color: 'preview.textMuted',
      fontSize: '2xs',
      fontWeight: 'bold',
    },
    code: {
      m: '0',
      p: '5',
      overflow: 'auto',
      color: 'preview.codeText',
      fontFamily: 'previewMono',
      fontSize: 'xs',
      lineHeight: '1.7',
      whiteSpace: 'pre',
    },
    overlay: {
      position: 'absolute',
      inset: '0',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '2',
      color: 'white',
      bg: 'preview.renderOverlay',
      backdropFilter: 'blur(2px)',
      fontSize: 'sm',
      fontWeight: 'bold',
    },
  },
  variants: {
    selected: {
      true: {
        modeButton: {
          color: 'preview.accentInk',
          bg: 'preview.accent',
          _hover: { color: 'preview.accentInk', bg: 'preview.accentHover' },
        },
      },
      false: {
        modeButton: {
          color: 'preview.textMuted',
          bg: 'transparent',
          _hover: { color: 'preview.text', bg: 'preview.hover' },
        },
      },
    },
  },
  defaultVariants: { selected: false },
});

export const previewInspectorSlotRecipe = defineSlotRecipe({
  className: 'chakra-email-preview-inspector',
  slots: [
    'root',
    'header',
    'eyebrow',
    'dirty',
    'fieldLabel',
    'control',
    'textarea',
    'primaryAction',
    'sendRoot',
    'sendHeader',
    'sendFields',
    'sendInput',
    'sendAction',
    'sendFeedback',
    'notice',
    'lintRoot',
    'lintHeader',
    'lintEmpty',
    'lintList',
    'lintItem',
    'lintReference',
  ],
  base: {
    root: {
      minW: '0',
      gap: '4',
      p: '4',
      borderLeftWidth: '1px',
      borderColor: 'preview.border',
      borderRadius: '0',
      bg: 'preview.panelTranslucent',
      boxShadow: 'none',
      h: 'full',
      overflowY: 'auto',
    },
    header: { alignItems: 'start', justifyContent: 'space-between' },
    eyebrow: {
      mb: '1',
      color: 'preview.textSubtle',
      fontSize: '2xs',
      fontWeight: 'extrabold',
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
    },
    dirty: { color: 'preview.warning', bg: 'preview.warningSoft' },
    fieldLabel: { color: 'preview.textSubtle', fontSize: 'xs' },
    control: { borderColor: 'preview.borderStrong' },
    textarea: {
      minH: '260px',
      resize: 'vertical',
      borderColor: 'preview.borderStrong',
      color: 'preview.text',
      bg: 'preview.raised',
      fontFamily: 'previewMono',
      fontSize: 'xs',
      _focusVisible: {
        borderColor: 'preview.accent',
        boxShadow: '0 0 0 1px var(--chakra-colors-preview-accent)',
      },
    },
    primaryAction: {
      minH: '8',
      color: 'preview.accentInk',
      bg: 'preview.accent',
      boxShadow: 'previewAccent',
      fontSize: 'xs',
      fontWeight: 'extrabold',
      _hover: { bg: 'preview.accentHover' },
    },
    sendRoot: {
      gap: '3',
      pt: '4',
      borderTopWidth: '1px',
      borderColor: 'preview.border',
    },
    sendHeader: {},
    sendFields: { gap: '3' },
    sendInput: {
      borderColor: 'preview.borderStrong',
      color: 'preview.text',
      bg: 'preview.raised',
      fontSize: 'xs',
      _focusVisible: {
        borderColor: 'preview.accent',
        boxShadow: '0 0 0 1px var(--chakra-colors-preview-accent)',
      },
    },
    sendAction: {
      minH: '8',
      borderWidth: '1px',
      borderColor: 'preview.borderStrong',
      color: 'preview.text',
      bg: 'preview.raised',
      fontSize: 'xs',
      fontWeight: 'bold',
      _hover: { bg: 'preview.hover' },
    },
    sendFeedback: { fontSize: '2xs' },
    notice: {
      gap: '2',
      p: '3',
      borderWidth: '1px',
      borderColor: 'preview.border',
      borderRadius: 'md',
      color: 'preview.textMuted',
      bg: 'preview.soft',
      fontSize: '2xs',
    },
    lintRoot: {
      gap: '3',
      pt: '4',
      borderTopWidth: '1px',
      borderColor: 'preview.border',
    },
    lintHeader: {
      alignItems: 'start',
      justifyContent: 'space-between',
      gap: '3',
    },
    lintEmpty: {
      gap: '2',
      p: '3',
      borderWidth: '1px',
      borderColor: 'preview.successBorder',
      borderRadius: 'md',
      color: 'preview.text',
      bg: 'preview.accentSoft',
      fontSize: 'xs',
    },
    lintList: { gap: '2', m: '0', p: '0', listStyleType: 'none' },
    lintItem: {
      p: '3',
      borderWidth: '1px',
      borderColor: 'preview.border',
      borderRadius: 'md',
      bg: 'preview.soft',
    },
    lintReference: {
      display: 'inline-block',
      mt: '2',
      color: 'preview.accent',
      fontSize: '2xs',
      fontWeight: 'bold',
      textDecoration: 'underline',
    },
  },
});

export const previewFeedbackSlotRecipe = defineSlotRecipe({
  className: 'chakra-email-preview-feedback',
  slots: ['error', 'tooltip', 'iconButton'],
  base: {
    iconButton: {
      '--preview-icon-button-size': { base: '44px', md: '32px' },
      w: 'var(--preview-icon-button-size)',
      minW: 'var(--preview-icon-button-size)',
      h: 'var(--preview-icon-button-size)',
      minH: 'var(--preview-icon-button-size)',
      p: '0',
      flexShrink: '0',
    },
    error: {
      mb: '4',
      borderWidth: '1px',
      borderColor: 'preview.danger',
      borderRadius: 'md',
      color: 'preview.text',
      bg: 'preview.dangerSoft',
    },
    tooltip: {
      maxW: '260px',
    },
  },
});

export const previewSlotRecipes = {
  [previewSlotRecipeKeys.feedback]: previewFeedbackSlotRecipe,
  [previewSlotRecipeKeys.inspector]: previewInspectorSlotRecipe,
  [previewSlotRecipeKeys.templates]: previewTemplatesSlotRecipe,
  [previewSlotRecipeKeys.viewer]: previewViewerSlotRecipe,
  [previewSlotRecipeKeys.workspace]: previewWorkspaceSlotRecipe,
};

const previewTheme = defineConfig({
  globalCss: {
    'html, body, #app': {
      minWidth: '320px',
      minHeight: '100%',
      margin: '0',
    },
    body: {
      minHeight: '100vh',
      overflow: 'hidden',
      color: 'preview.text',
      background: 'preview.canvas',
      fontFamily: 'preview',
      fontSynthesis: 'none',
      textRendering: 'optimizeLegibility',
    },
    '*': {
      boxSizing: 'border-box',
    },
    'button, select, textarea': {
      font: 'inherit',
    },
  },
  theme: {
    tokens: {
      fonts: {
        preview: {
          value:
            'Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        },
        previewMono: {
          value: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
        },
      },
      shadows: {
        previewPanel: { value: '0 1px 3px rgba(0, 0, 0, 0.08)' },
        previewAccent: { value: '0 1px 2px rgba(0, 0, 0, 0.12)' },
      },
    },
    semanticTokens: {
      colors: {
        preview: {
          canvas: { value: { _light: '#f5f5f5', _dark: '#0a0a0a' } },
          panel: { value: { _light: '#ffffff', _dark: '#171717' } },
          raised: { value: { _light: '#fafafa', _dark: '#1f1f1f' } },
          soft: { value: { _light: '#f0f0f0', _dark: '#262626' } },
          chrome: {
            value: {
              _light: 'rgba(255, 255, 255, 0.96)',
              _dark: 'rgba(10, 10, 10, 0.96)',
            },
          },
          sidebar: {
            value: {
              _light: '#fafafa',
              _dark: '#111111',
            },
          },
          panelTranslucent: {
            value: {
              _light: 'rgba(255, 255, 255, 0.96)',
              _dark: 'rgba(23, 23, 23, 0.96)',
            },
          },
          overlay: {
            value: {
              _light: 'rgba(245, 245, 245, 0.9)',
              _dark: 'rgba(31, 31, 31, 0.9)',
            },
          },
          hover: {
            value: {
              _light: 'rgba(0, 0, 0, 0.045)',
              _dark: 'rgba(255, 255, 255, 0.055)',
            },
          },
          border: { value: { _light: '#e5e5e5', _dark: '#2e2e2e' } },
          borderStrong: {
            value: { _light: '#d4d4d4', _dark: '#464646' },
          },
          text: { value: { _light: '#171717', _dark: '#f5f5f5' } },
          textSubtle: {
            value: { _light: '#525252', _dark: '#b3b3b3' },
          },
          textMuted: {
            value: { _light: '#737373', _dark: '#8c8c8c' },
          },
          accent: { value: { _light: '#171717', _dark: '#f5f5f5' } },
          accentStrong: {
            value: { _light: '#0a0a0a', _dark: '#ffffff' },
          },
          accentHover: {
            value: { _light: '#303030', _dark: '#dddddd' },
          },
          accentInk: { value: { _light: '#ffffff', _dark: '#171717' } },
          accentSoft: {
            value: {
              _light: 'rgba(0, 0, 0, 0.065)',
              _dark: 'rgba(255, 255, 255, 0.1)',
            },
          },
          successBorder: {
            value: {
              _light: 'rgba(0, 0, 0, 0.18)',
              _dark: 'rgba(255, 255, 255, 0.2)',
            },
          },
          danger: { value: { _light: '#c53d35', _dark: '#ff8178' } },
          dangerBorder: {
            value: {
              _light: 'rgba(197, 61, 53, 0.28)',
              _dark: 'rgba(255, 129, 120, 0.3)',
            },
          },
          dangerSoft: {
            value: {
              _light: 'rgba(197, 61, 53, 0.1)',
              _dark: 'rgba(255, 129, 120, 0.12)',
            },
          },
          warning: { value: { _light: '#936000', _dark: '#f4bd6c' } },
          warningBorder: {
            value: {
              _light: 'rgba(147, 96, 0, 0.28)',
              _dark: 'rgba(244, 189, 108, 0.3)',
            },
          },
          warningSoft: {
            value: {
              _light: 'rgba(147, 96, 0, 0.1)',
              _dark: 'rgba(244, 189, 108, 0.12)',
            },
          },
          previewLight: { value: '#e8eaed' },
          previewDark: { value: '#0a0a0a' },
          previewFrameDark: { value: '#171717' },
          codeCanvas: { value: { _light: '#171717', _dark: '#0a0a0a' } },
          codeText: { value: '#d4d4d4' },
          renderOverlay: { value: 'rgba(10, 10, 10, 0.72)' },
        },
      },
    },
    slotRecipes: previewSlotRecipes,
  },
});

export function createPreviewSystem(theme: Record<string, unknown> = {}) {
  return createSystem(
    defaultConfig,
    previewTheme,
    defineConfig({ theme: theme as SystemConfig['theme'] }),
  );
}
